// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3DpkHmKNGY8Swdbo0LmvO5xGzTCnYns',
    appId: '1:531825533314:web:3dd16c4ce3e58cfa0f2f9b',
    messagingSenderId: '531825533314',
    projectId: 'habits-81e2b',
    authDomain: 'habits-81e2b.firebaseapp.com',
    storageBucket: 'habits-81e2b.firebasestorage.app',
    measurementId: 'G-N8JY5QHFK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLMzTMlXilrTcnroR9hZpM0OvCNOs2Cnw',
    appId: '1:531825533314:android:9d0c0c7b3225e0b50f2f9b',
    messagingSenderId: '531825533314',
    projectId: 'habits-81e2b',
    storageBucket: 'habits-81e2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwxp-tHnocL_XYOS4_wC5P7Kw-znrQsZY',
    appId: '1:531825533314:ios:453effa8474e402c0f2f9b',
    messagingSenderId: '531825533314',
    projectId: 'habits-81e2b',
    storageBucket: 'habits-81e2b.firebasestorage.app',
    iosBundleId: 'com.example.habits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN3DpkHmKNGY8Swdbo0LmvO5xGzTCnYns',
    appId: '1:531825533314:web:7092b8a19f9bd8cf0f2f9b',
    messagingSenderId: '531825533314',
    projectId: 'habits-81e2b',
    authDomain: 'habits-81e2b.firebaseapp.com',
    storageBucket: 'habits-81e2b.firebasestorage.app',
    measurementId: 'G-D63L6BBVNH',
  );
}
